Adding link for detailed instructions
lightninglabs/lightning-terminal pull request #218
Opened 2021-05-01 14:35 UTC by keblek

LiT links to this after installing.

2021-05-03 08:56 UTC, guggero reviewed
Thanks for the PR, that link is definitely useful to have in there.
Just a small suggestion in the wording, otherwise LGTM!

2021-05-03 08:56 UTC, guggero commented on README.md
> +Additionally you find detailed instructions in the [lightning engineering docs](https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/get-lit).
```suggestion
Additionally you find detailed instructions on the [docs.lightning.engineering](https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/get-lit) page.
```

2021-05-03 09:49 UTC, keblek commented
Sure thing!

2021-05-03 10:59 UTC, guggero approved these changes

2021-05-03 13:38 UTC, jamaljsr requested changes
Good idea to add this link. Thanks.

I just suggested a small grammar improvement.

2021-05-03 13:38 UTC, jamaljsr commented on README.md
> +Additionally you find detailed instructions on the [docs.lightning.engineering](https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/get-lit) page.
```suggestion
Additionally, you can find detailed instructions on the [docs.lightning.engineering](https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/get-lit) page.
```

2021-05-04 10:18 UTC, matthiasdebernardini approved these changes
thanks!

2021-05-04 11:08 UTC, merged