ui+auth: updates login page view
lightninglabs/lightning-terminal pull request #553
Opened 2023-05-17 01:12 UTC by dstrukt

Not sure why the test is failing, I've removed that snippet of code in the test..

Current:
<img width="1181" alt="Screen Shot 2023-05-16 at 6 10 39 PM" src="https://github.com/lightninglabs/lightning-terminal/assets/6250771/9e30e49f-85a5-4d7e-a964-c9c894166272">

Proposed:
<img width="986" alt="Screen Shot 2023-05-17 at 9 49 44 AM" src="https://github.com/lightninglabs/lightning-terminal/assets/6250771/231eeca3-d0e3-4305-8813-c59a2a5afc59">
<img width="985" alt="Screen Shot 2023-05-17 at 9 49 52 AM" src="https://github.com/lightninglabs/lightning-terminal/assets/6250771/3f9f517e-c78c-4585-97bb-1c371f39bcbf">
<img width="986" alt="Screen Shot 2023-05-17 at 9 50 02 AM" src="https://github.com/lightninglabs/lightning-terminal/assets/6250771/01d65b09-af67-4fb3-aa5d-081007545746">

2023-05-24 18:51 UTC, lightninglabs-deploy commented
@itsrachelfish: review reminder
@jbrill: review reminder

2023-05-31 19:16 UTC, lightninglabs-deploy commented
@itsrachelfish: review reminder
@jbrill: review reminder

2023-06-07 20:15 UTC, lightninglabs-deploy commented
@itsrachelfish: review reminder
@jbrill: review reminder

2023-06-14 20:19 UTC, lightninglabs-deploy commented
@itsrachelfish: review reminder
@jbrill: review reminder

2023-06-21 20:34 UTC, lightninglabs-deploy commented
@itsrachelfish: review reminder
@jbrill: review reminder

2023-06-28 20:43 UTC, lightninglabs-deploy commented
@itsrachelfish: review reminder
@jbrill: review reminder

2023-07-05 21:10 UTC, lightninglabs-deploy commented
@itsrachelfish: review reminder
@jbrill: review reminder

2023-07-12 21:59 UTC, lightninglabs-deploy commented
@itsrachelfish: review reminder
@jbrill: review reminder

2023-07-19 21:59 UTC, lightninglabs-deploy commented
@itsrachelfish: review reminder
@jbrill: review reminder

2023-07-26 22:53 UTC, lightninglabs-deploy commented
@itsrachelfish: review reminder
@jbrill: review reminder

2023-08-02 23:05 UTC, lightninglabs-deploy commented
@itsrachelfish: review reminder
@jbrill: review reminder

2023-08-09 23:15 UTC, lightninglabs-deploy commented
@itsrachelfish: review reminder
@jbrill: review reminder

2023-08-16 06:26 UTC, itsrachelfish requested changes
@dstrukt Is the sidebar supposed to look like this? :sweat_smile: It doesn't seem to match the color scheme of the background.

![Screenshot from 2023-08-16 00-22-25](https://github.com/lightninglabs/lightning-terminal/assets/1670549/23ce2d29-1d74-48d2-ab9e-9aa8ccba02c4)

Additionally, I noticed that the background gradient only fills 1 viewport height. When the page is longer than the screen and you scroll down, the background color changes

![Screenshot from 2023-08-16 00-23-52](https://github.com/lightninglabs/lightning-terminal/assets/1670549/1214f83c-f589-4f3f-a6d9-d755f5d8f04f)

2023-08-23 07:21 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2023-08-30 21:58 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2023-09-06 22:49 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2023-09-18 06:50 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2023-09-25 07:24 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2023-10-02 07:41 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2023-10-09 08:06 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2023-10-16 08:19 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2023-10-30 08:40 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2023-11-06 09:10 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2023-11-13 09:37 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2023-11-20 10:19 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2023-11-27 11:17 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2023-12-11 12:46 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2023-12-18 13:39 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2023-12-25 14:14 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2024-01-02 21:04 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2024-01-09 21:21 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2024-01-16 22:22 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2024-01-23 23:16 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2024-01-31 00:15 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2024-02-07 01:01 UTC, lightninglabs-deploy commented
@jbrill: review reminder
@dstrukt, remember to re-request review from reviewers when ready

2024-02-12 06:36 UTC, lightninglabs-deploy commented
Closing due to inactivity

2024-02-12 07:40 UTC, lightninglabs-deploy commented
Closing due to inactivity

2024-02-12 08:43 UTC, lightninglabs-deploy commented
Closing due to inactivity

2024-02-12 09:44 UTC, lightninglabs-deploy commented
Closing due to inactivity

2024-02-12 10:48 UTC, lightninglabs-deploy commented
Closing due to inactivity

2024-02-12 11:50 UTC, lightninglabs-deploy commented
Closing due to inactivity

2024-02-12 12:55 UTC, lightninglabs-deploy commented
Closing due to inactivity

2024-02-12 13:56 UTC, lightninglabs-deploy commented
Closing due to inactivity

2024-02-12 14:58 UTC, lightninglabs-deploy commented
Closing due to inactivity

2024-02-12 15:00 UTC, guggero commented
!lightninglabs-deploy mute

2025-09-08 20:20 UTC, closed without merging