build: update to lnd v0.17.0 and latest version of Pool
lightninglabs/lightning-terminal pull request #633
Opened 2023-08-24 23:18 UTC by Roasbeef

We point to the rc for 0.17.0 for now. Also we had to update Pool as well, due to a replace directive inserted into lnd.

2023-08-30 05:19 UTC, ellemouton requested changes
The README needs to be updated. One of the CI checks is also failing. I also think we will wait till the final 0.17.0-beta is released before merging this

2023-09-06 06:01 UTC, lightninglabs-deploy commented
@roasbeef, remember to re-request review from reviewers when ready

2023-09-13 06:31 UTC, lightninglabs-deploy commented
@roasbeef, remember to re-request review from reviewers when ready

2023-09-20 07:20 UTC, lightninglabs-deploy commented
@roasbeef, remember to re-request review from reviewers when ready

2023-09-27 07:48 UTC, lightninglabs-deploy commented
@roasbeef, remember to re-request review from reviewers when ready

2023-09-28 09:41 UTC, guggero commented
Replaced by https://github.com/lightninglabs/lightning-terminal/pull/645.

2023-09-28 09:41 UTC, closed without merging